title: AmeriCal Youth Symphony
description: "Young musicians. One remarkable sound."
owner_name: AmeriCal Youth Symphony
baseurl: ""
github_repo: "americalys"
future: true
remote_theme: jekyll/minima
minima:
  skin: auto
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
header_pages: []
